/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestPlugin;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        ProjectL2 classUnderTest = new ProjectL2();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
